=== mark-moseley/Netbeans/testtools/src/org/netbeans/modules/testtools/xtest-cfg-1_0.dtd
<!-- DTD for xtest cfg files -->
<!--
                Sun Public License Notice

The contents of this file are subject to the Sun Public License
Version 1.0 (the "License"). You may not use this file except in
compliance with the License. A copy of the License is available at
http://www.sun.com/

The Original Code is NetBeans. The Initial Developer of the Original
Code is Sun Microsystems, Inc. Portions Copyright 1997-2002 Sun
Microsystems, Inc. All Rights Reserved.
-->


<!ELEMENT mconfig (testbag+,executor+,compiler*,resultsprocessor+)>
<!ATTLIST mconfig
    name CDATA #REQUIRED
>

<!ELEMENT testbag (testproperty*,testset+)>
<!ATTLIST testbag
    name             CDATA #REQUIRED
    testattribs	     CDATA #REQUIRED
    executor         CDATA #IMPLIED
    compiler         CDATA #IMPLIED
    resultsprocessor CDATA #IMPLIED
    prio             NMTOKEN #IMPLIED
>

<!ELEMENT testproperty EMPTY>
<!ATTLIST testproperty
    name  CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!ELEMENT testset (patternset*)>
<!ATTLIST testset
    dir CDATA #REQUIRED
>

<!ELEMENT patternset ((include|exclude)*)>
<!ELEMENT include EMPTY>
<!ATTLIST include 
    name CDATA #REQUIRED
>

<!ELEMENT exclude EMPTY>
<!ATTLIST exclude 
    name CDATA #REQUIRED
>

<!ELEMENT executor EMPTY>
<!ATTLIST executor
    name    CDATA #REQUIRED
    antfile CDATA #IMPLIED
    target  CDATA #IMPLIED
    dir     CDATA #IMPLIED
    default (true|false|yes|no|0|1) "false"
>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
    name    CDATA #REQUIRED
    antfile CDATA #IMPLIED
    target  CDATA #IMPLIED
    dir     CDATA #IMPLIED
    default (true|false|yes|no|0|1) "false"
>

<!ELEMENT resultsprocessor EMPTY>
<!ATTLIST resultsprocessor
    name    CDATA #REQUIRED
    antfile CDATA #IMPLIED
    target  CDATA #IMPLIED
    dir     CDATA #IMPLIED
    default (true|false|yes|no|0|1) "false"
>

=== mark-moseley/Netbeans/j2ee.jboss4/test/cfg-qa-functional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mconfig PUBLIC "-//NetBeans//DTD XTest cfg 1.0//EN" "http://www.netbeans.org/dtds/xtest-cfg-1_0.dtd">
<!--
The contents of this file are subject to the terms of the Common Development
and Distribution License (the License). You may not use this file except in
compliance with the License.

You can obtain a copy of the License at http://www.netbeans.org/cddl.html
or http://www.netbeans.org/cddl.txt.

When distributing Covered Code, include this CDDL Header Notice in each file
and include the License file at http://www.netbeans.org/cddl.txt.
If applicable, add the following below the CDDL Header, with the fields
enclosed by brackets [] replaced by your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

The Original Software is NetBeans. The Initial Developer of the Original
Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
Microsystems, Inc. All Rights Reserved.
-->

<mconfig name="Configuration of JBoss4 unit tests">

    <testbag testattribs="dev-api" executor="ide" name="JBoss4 API Validation tests">
        <testset dir="qa-functional/src">
            <patternset>
                <include name="org/netbeans/modules/j2ee/jboss4/test/JBoss4TestSuite.class"/>
            </patternset>
        </testset>
    </testbag>

    <testbag testattribs="dev-ui" executor="ide" name="JBoss4 UI Validation tests">
        <testset dir="qa-functional/src">
            <patternset>
                <include name="org/netbeans/test/j2ee/jboss4/JBossValidation.class"/>
            </patternset>
        </testset>
    </testbag>
 
    <!-- ide executor - use this one if you plan to run your tests inside IDE (internally).
    Similarly as with code executor, you can create your own to 
    prepare some neccessary stuff before running tests. -->
    <executor name="ide" antfile="build-qa-functional.xml" target="runidetest" default="true"/>
    <compiler name="qa-functional-compiler" antfile="build-qa-functional.xml" target="qa-functional-compiler" default="true"/>
</mconfig>

=== mark-moseley/Netbeans/java.lexer/test/cfg-unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mconfig PUBLIC "-//NetBeans//DTD XTest cfg 1.0//EN" "http://www.netbeans.org/dtds/xtest-cfg-1_0.dtd">
<!--
The contents of this file are subject to the terms of the Common Development
and Distribution License (the License). You may not use this file except in
compliance with the License.

You can obtain a copy of the License at http://www.netbeans.org/cddl.html
or http://www.netbeans.org/cddl.txt.

When distributing Covered Code, include this CDDL Header Notice in each file
and include the License file at http://www.netbeans.org/cddl.txt.
If applicable, add the following below the CDDL Header, with the fields
enclosed by brackets [] replaced by your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

The Original Software is NetBeans. The Initial Developer of the Original
Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
Microsystems, Inc. All Rights Reserved.
-->

<!--
  These classes are excluded by default (defined in build.xml):
    "**/*Suite.class"
    "**/*$$*.class"
    "**/data/**"
    "**/hidden/**"
    "**/*Hidden.*"
    "**/*Hid.*"
-->

<mconfig name="java lexer unit test config">

    <testbag testattribs="stable" executor="code" name="testbag_1">
        <testset dir="unit/src">
            <patternset>
                <include name="**/**Test.class"/>
            </patternset>
        </testset>
    </testbag>
    
    <testbag testattribs="failing" executor="code" name="testbag_2">
        <testset dir="unit/src">
            <patternset>
            </patternset>
        </testset>
    </testbag>
    
    <!-- If you want to use this testbag you *must* provide xtest.includes property, -->
    <!-- (either on cmd line or in the script) to explicitly define which test       -->
    <!-- you want to run. This will run *only* tests from unit/src folder !!!        -->
    <testbag testattribs="empty" executor="code" name="testbag_empty">
        <testset dir="unit/src"/>
    </testbag>

    <executor name="code" antfile="../../../nbbuild/templates/xtest-unit.xml" target="run-unit-test"/>
    
    <compiler name="unit-compiler" antfile="../../../nbbuild/templates/xtest-unit.xml" target="default-compiler" default="true"/>
    
</mconfig>
