<?xml version="1.0" encoding="UTF-8"?>
<!--
 The contents of this file are subject to the terms of the Common Development
 and Distribution License (the License). You may not use this file except in
 compliance with the License.
 
 You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 or http://www.netbeans.org/cddl.txt.
 
 When distributing Covered Code, include this CDDL Header Notice in each file
 and include the License file at http://www.netbeans.org/cddl.txt.
 If applicable, add the following below the CDDL Header, with the fields
 enclosed by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 The Original Software is NetBeans. The Initial Developer of the Original
 Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
 Microsystems, Inc. All Rights Reserved.
-->
<!DOCTYPE component_type_group [

<!ENTITY R    "read">
<!ENTITY RW   "read,write">

<!ELEMENT component_type_group (property_group*,component_type_group*, component_type*)>
<!ATTLIST component_type_group
icon CDATA #REQUIRED
name CDATA #REQUIRED
title CDATA #REQUIRED
description CDATA #REQUIRED
>
<!ELEMENT property_group (property_group*, property*)>
<!ATTLIST property_group
name CDATA #IMPLIED
ref CDATA #IMPLIED
>
<!ELEMENT component_type (property_group*, property*, component_type*, code*)>
<!ATTLIST component_type
allowsChildren CDATA #IMPLIED
icon CDATA #IMPLIED
name CDATA #IMPLIED
extends CDATA #IMPLIED
title CDATA #IMPLIED
description CDATA #IMPLIED
visible CDATA #IMPLIED
validator CDATA #IMPLIED
>
<!ELEMENT property (script*)>
<!ATTLIST property
access CDATA #IMPLIED
category CDATA #IMPLIED
default CDATA #IMPLIED
title CDATA #IMPLIED
description CDATA #IMPLIED
editor CDATA #IMPLIED
multiple CDATA #IMPLIED
name CDATA #IMPLIED
renderer CDATA #IMPLIED
required CDATA #IMPLIED
script CDATA #IMPLIED
transient CDATA #IMPLIED
type CDATA #IMPLIED
>
<!ELEMENT script (#PCDATA)>

<!ELEMENT code EMPTY>
<!ATTLIST code
file CDATA #REQUIRED
type CDATA #REQUIRED
>

]>

<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Bing Lu (SeeBeyond) -->
<component_type_group name="IEP" icon="" title="IEP.title" description="IEP.description">
    <component_type_group name="View" icon="" title="IEP.View.title" description="IEP.View.description">
        <property_group name="Node">
            <property transient="false" category="layout" name="x" title="IEP.View.Node.x.title" description="IEP.View.Node.x.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="0" renderer="string" access="" multiple="false"/>
            <property transient="false" category="layout" name="y" title="IEP.View.Node.y.title" description="IEP.View.Node.y.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="0" renderer="string" access="" multiple="false"/>
            <property transient="false" category="layout" name="z" title="IEP.View.Node.z.title" description="IEP.View.Node.z.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="0" renderer="string" access="" multiple="false"/>
        </property_group>
    </component_type_group>
    <!-- Model -->
    <component_type_group name="Model" icon="" title="IEP.Model.title" description="IEP.Model.description">
        <property_group name="Entity">
            <property transient="true" category="IEP.Category.main" name="propertyEditor" title="IEP.Model.Entity.propertyEditor.title" description="IEP.Model.Entity.propertyEditor.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="name" title="IEP.Model.Entity.name.title" description="IEP.Model.Entity.name.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.AlphaNumericNamePropertyEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="id" title="IEP.Model.Entity.id.title" description="IEP.Model.Entity.id.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&R;" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="type" title="IEP.Model.Entity.type.title" description="IEP.Model.Entity.type.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="Entity" renderer="string" access="&R;" multiple="false"/>
            <property transient="false" category="IEP.Category.schema" name="inputSchemaIdList" title="IEP.Model.Entity.inputSchemaIdList.title" description="IEP.Model.Entity.inputSchemaIdList.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&R;" multiple="true"/>
            <property transient="false" category="IEP.Category.schema" name="outputSchemaId" title="IEP.Model.Entity.outputSchemaId.title" description="IEP.Model.Entity.outputSchemaId.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&R;" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="description" title="IEP.Model.Entity.description.title" description="IEP.Model.Entity.description.description" required="false" type="string" editor="default" default="" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="topoScore" title="IEP.Model.Entity.topoScore.title" description="IEP.Model.Entity.topoScore.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="0" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="inputType" title="IEP.Model.Entity.inputType.title" description="IEP.Model.Entity.inputType.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="i18n.IEP.IOType.none" renderer="string" access="&R;" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="outputType" title="IEP.Model.Entity.outputType.title" description="IEP.Model.Entity.outputType.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="i18n.IEP.IOType.none" renderer="string" access="&R;" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="inputMaxCount" title="IEP.Model.Entity.inputMaxCount.title" description="IEP.Model.Entity.inputMaxCount.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="1" renderer="string" access="&R;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="inputIdList" title="IEP.Model.Entity.inputIdList.title" description="IEP.Model.Entity.inputIdList.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.InputIdListNoEditEditor" default="" renderer="string" access="&R;" multiple="true"/>
            <property transient="true" category="IEP.Category.entity" name="staticInputMaxCount" title="IEP.Model.Entity.staticInputMaxCount.title" description="IEP.Model.Entity.staticInputMaxCount.description" required="false" type="integer" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="0" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="staticInputIdList" title="IEP.Model.Entity.staticInputIdList.title" description="IEP.Model.Entity.staticInputIdList.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.StaticInputIdListNoEditEditor" default="" renderer="string" access="" multiple="true"/>
            <property transient="true" category="IEP.Category.entity" name="isSchemaOwner" title="IEP.Model.Entity.isSchemaOwner.title" description="IEP.Model.Entity.isSchemaOwner.description" required="false" type="boolean" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="false" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="isGlobal" title="IEP.Model.Entity.isGlobal.title" description="IEP.Model.Entity.isGlobal.description" required="false" type="boolean" editor="default" default="false" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="globalId" title="IEP.Model.Entity.globalId.title" description="IEP.Model.Entity.globalId.description" required="false" type="string" editor="default" default="" renderer="string" access="" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="wsInput" title="IEP.Model.Entity.wsInput.title" description="IEP.Model.Entity.wsInput.description" required="false" type="boolean" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="false" renderer="string" access="" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="wsOutput" title="IEP.Model.Entity.wsOutput.title" description="IEP.Model.Entity.wsOutput.description" required="false" type="boolean" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="false" renderer="string" access="" multiple="false"/>
            <property transient="false" category="IEP.Category.entity" name="batchMode" title="IEP.Model.Entity.batchMode.title" description="IEP.Model.Entity.batchMode.description" required="false" type="boolean" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="false" renderer="string" access="" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="palette" title="IEP.Model.Entity.palette.title" description="IEP.Model.Entity.palette.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="helpID" title="IEP.Model.Entity.helpID.title" description="IEP.Model.Entity.helpID.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="iep_work_iepops" renderer="string" access="" multiple="false"/>
            <property transient="true" category="IEP.Category.entity" name="categoryOrder" title="IEP.Model.Entity.categoryOrder.title" description="IEP.Model.Entity.categoryOrder.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="IEP.Category.main\IEP.Category.entity\IEP.Category.schema" renderer="string" access="" multiple="true"/>
        </property_group>
        <component_type name="Plan" icon="" title="IEP.Model.Plan.title" description="IEP.Model.Plan.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.model.DefaultPlanValidator">
            <property transient="false" category="IEP.Category.model" required="false" name="version" title="IEP.Model.Plan.version.title" description="IEP.Model.Plan.version.description" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="1.0" renderer="string" access="&R;" multiple="false"/>
            <property transient="true" category="IEP.Category.model" required="false" name="doc" title="IEP.Model.Plan.doc.title" description="IEP.Model.Plan.doc.description" type="object" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="docObj" access="&R;" multiple="false"/>
            
            <component_type name="Metadata" icon="" title="IEP.Model.Plan.Metadata.title" description="IEP.Model.Plan.Metadata.description" allowsChildren="true" visible="false"  validator="org.netbeans.modules.iep.editor.tcg.model.OkValidator">
                <component_type name="View" icon="" title="View" description="IEP.Model.Plan.Metadata.View.description" allowsChildren="true" visible="false"  validator="org.netbeans.modules.iep.editor.tcg.model.OkValidator">
                    <property transient="false" category="this" required="false" name="orthoflow" title="IEP.Model.Plan.Metadata.View.orthoflow.title" description="IEP.Model.Plan.Metadata.View.orthoflow.description" type="boolean" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="false" renderer="string" access="" multiple="false"/>
                </component_type>
            </component_type>
            
            <component_type name="Schemas" icon="" title="IEP.Model.Plan.Schemas.title" description="IEP.Model.Plan.Schemas.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.OkValidator">
                <code type="xml" file="vm/iep/model/group.xml"/>            
            </component_type>
            
            <component_type name="Operators" icon="" title="IEP.Model.Plan.Operators.title" description="IEP.Model.Plan.Operators.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.DefaultValidator">
                <code type="xml" file="vm/iep/model/group.xml"/>            
            </component_type>
            
            <component_type name="Links" icon="" title="IEP.Model.Plan.Links" description="IEP.Model.Plan.Links.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.OkValidator">
                <code type="xml" file="vm/iep/model/group.xml"/>            
            </component_type>
            
            <code type="xml" file="vm/iep/model/plan.xml"/>            
        </component_type>
        <component_type name="Link" icon="" title="IEP.Model.Link.title" description="IEP.Model.Link.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.OkValidator">
            <property transient="false" category="this" required="false" name="name" title="IEP.Model.Link.name.title" description="IEP.Model.Link.name.description" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="" multiple="false"/>
            <property transient="false" category="this" required="false" name="from" title="IEP.Model.Link.from.title" description="IEP.Model.Link.from.description" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="" multiple="false"/>
            <property transient="false" category="this" required="false" name="to" title="IEP.Model.Link.to.title" description="IEP.Model.Link.to.description" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="" multiple="false"/>
        </component_type>
    </component_type_group>

    <!-- Metadata -->
    <component_type_group name="Metadata" icon="" title="IEP.Metadata.title" description="IEP.Metadata.description">
        <!-- column -->
        <component_type name="ColumnMetadata" icon="" title="IEP.Metadata.ColumnMetadata.title" description="IEP.Metadata.ColumnMetada.description" allowsChildren="false" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.DefaultValidator">
            <property transient="false" category="this" name="name" title="IEP.Metadata.ColumnMetadata.name.title" description="IEP.Metadata.ColumnMetadata.name.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="this" name="type" title="IEP.Metadata.ColumnMetadata.type.title" description="IEP.Metadata.ColumnMetadata.type.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="this" name="size" title="IEP.Metadata.ColumnMetadata.size.title" description="IEP.Metadata.ColumnMetadata.size.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="this" name="scale" title="IEP.Metadata.ColumnMetadata.scale.title" description="IEP.Metadata.ColumnMetadata.scale.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="this" name="comment" title="IEP.Metadata.ColumnMetadata.comment.title" description="IEP.Metadata.ColumnMetadata.comment.description" required="false" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.NoEditEditor" default="" renderer="string" access="&RW;" multiple="false"/>
            <code type="xml" file="vm/iep/metadata/columnMetadata.xml"/>
        </component_type>
        <!-- schema -->
        <component_type name="Schema" icon="" title="IEP.Metadata.Schema.title" description="IEP.Metadata.Schema.description" allowsChildren="true" visible="false" validator="org.netbeans.modules.iep.editor.tcg.model.DefaultValidator">
            <code type="xml" file="vm/iep/metadata/schema.xml"/>
        </component_type>
    </component_type_group>
    
    <!-- Input -->
    <component_type_group name="Input" icon="" title="IEP.Input.title" description="IEP.Input.description">
        <!-- stream input: creating table in db -->
        <component_type name="StreamInput" icon="streamInputx32.png" title="IEP.Input.StreamInput.title" description="IEP.Input.StreamInput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.DefaultCustomEditor"/>
                <property name="inputSchemaIdList" access="" />
                <property name="inputType" access="" />
                <property name="inputMaxCount" access="" />
	            <property name="inputIdList" access="" />
	            <property name="staticInputMaxCount" access="" />
    	        <property name="staticInputIdList" access="" />
                <property name="type" default="i18n.IEP.Input.StreamInput.title"/>
                <property name="outputType" default="i18n.IEP.IOType.stream"/>
                <property name="outputSchemaId" required="true"/>
                <property name="isSchemaOwner" default="true"/>
                <property name="wsInput" default="true"/>
                <property name="palette" default="input"/>
                <property name="helpID" default="iep_streaminput_prop"/>
            </property_group>
            <code type="xml" file="vm/iep/input/streamInput.xml"/>
        </component_type>
        <!-- relation input: creating table in db-->
        <component_type name="TableInput" icon="tableInputx32.png" title="IEP.Input.TableInput.title" description="IEP.Input.TableInput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.TableInputCustomEditor"/>
                <property name="inputSchemaIdList" access="" />
                <property name="inputType" access="" />
                <property name="inputMaxCount" access="" />
	            <property name="inputIdList" access="" />
	            <property name="staticInputMaxCount" access="" />
    	        <property name="staticInputIdList" access="" />
                <property name="type" default="i18n.IEP.Input.TableInput.title"/>
                <property name="outputType" default="i18n.IEP.IOType.table"/>
                <property name="outputSchemaId" required="true"/>
                <property name="isSchemaOwner" default="true"/>
                <property name="globalId" default="" access="&RW;"/>
                <property name="isGlobal" default="true" access="&R;"/>
                <property name="palette" default="input"/>
                <property name="helpID" default="iep_tableinput_propedit"/>
            </property_group>
            <code type="xml" file="vm/iep/input/relationInput.xml"/>
        </component_type>
    </component_type_group>
    <!-- Output -->
    <component_type_group name="Output" icon="" title="IEP.Output.title" description="IEP.Output.description">
        <!-- stream output: do nothing -->
        <component_type name="StreamOutput" icon="streamOutputx32.png" title="IEP.Output.StreamOutput.title" description="IEP.Output.StreamOutput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.DynamicOutputCustomEditor"/>
                <property name="type" default="i18n.IEP.Output.StreamOutput.title"/>
                <property name="inputType" default="i18n.IEP.IOType.stream"/>
                <property name="wsOutput" default="true"/>
                <property name="palette" default="output"/>
                <property name="helpID" default="iep_streamout_propedit"/>
            </property_group>
            <property transient="false" category="IEP.Category.main" name="includeTimestamp" title="IEP.Output.StreamOutput.includeTimestamp.title" description="IEP.Output.StreamOutput.includeTimestamp.description" required="false" type="boolean" editor="default" default="false" renderer="string" access="&RW;" multiple="false"/>
            <code type="xml" file="vm/iep/output/streamOutput.xml"/>
        </component_type>
        <!-- batched stream ouput: do nothing -->
        <component_type name="BatchedStreamOutput" icon="batchedStreamOutputx32.png" title="IEP.Output.BatchedStreamOutput.title" description="IEP.Output.BatchedStreamOutput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.BatchedStreamOutputCustomEditor"/>
                <property name="type" default="i18n.IEP.Output.BatchedStreamOutput.title"/>
                <property name="inputType" default="i18n.IEP.IOType.stream"/>
                <property name="wsOutput" default="true"/>
                <property name="batchMode" default="true"/>
                <property name="palette" default="output"/>
            </property_group>
            <property transient="false" category="IEP.Category.main" name="includeTimestamp" title="IEP.Output.BatchedStreamOutput.includeTimestamp.title" description="IEP.Output.BatchedStreamOutput.includeTimestamp.description" required="false" type="boolean" editor="default" default="false" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="batchSize" title="IEP.Output.BatchedStreamOutput.batchSize.title" description="IEP.Output.BatchedStreamOutput.batchSize.description" required="false" type="integer" editor="default" default="10" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="maximumDelaySize" title="IEP.Output.BatchedStreamOutput.maximumDelaySize.title" description="IEP.Output.BatchedStreamOutput.maximumDelaySize.description" required="false" type="double" editor="default" default="10.0" renderer="string" access="&RW;" multiple="false"/>
            <property transient="false" category="IEP.Category.main" name="maximumDelayUnit" title="IEP.Output.BatchedStreamOutput.maximumDelayUnit.title" description="IEP.Output.BatchedStreamOutput.maximumDelayUnit.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.TimeUnitPropertyEditor" default="second" renderer="string" access="&RW;" multiple="false"/>
            <code type="xml" file="vm/iep/output/batchedStreamOutput.xml"/>
        </component_type>
        <!-- relation output: do nothing -->
        <component_type name="RelationOutput" icon="relationOutputx32.png" title="IEP.Output.RelationOutput.title" description="IEP.Output.RelationOutput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.DynamicOutputCustomEditor"/>
                <property name="type" default="i18n.IEP.Output.RelationOutput.title"/>
                <property name="inputType" default="i18n.IEP.IOType.relation"/>
                <property name="wsOutput" default="true"/>
                <property name="palette" default="output"/>
                <property name="helpID" default="iep_relationout_propedit"/>
            </property_group>
            <property transient="false" category="IEP.Category.main" name="includeTimestamp" title="IEP.Output.RelationOutput.includeTimestamp.title" description="IEP.Output.RelationOutput.includeTimestamp.description" required="false" type="boolean" editor="default" default="false" renderer="string" access="&RW;" multiple="false"/>
            <code type="xml" file="vm/iep/output/relationOutput.xml"/>
        </component_type>
        <!-- relation output: use a table update info to maintain the table's state -->
        <component_type name="TableOutput"  icon="tableOutputx32.png" title="IEP.Output.TableOutput.title" description="IEP.Output.TableOutput.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.model.DefaultOperatorValidator">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.TableOutputCustomEditor"/>
                <property name="type" default="i18n.IEP.Output.TableOutput.title"/>
                <property name="inputType" default="i18n.IEP.IOType.relation"/>
                <property name="isGlobal" default="false" access="&RW;"/>
                <property name="globalId" default="" access="&RW;"/>
                <property name="palette" default="output"/>
                <property name="helpID" default="iep_tableout_propedit"/>
            </property_group>
            <code type="xml" file="vm/iep/output/tableOutput.xml"/>
        </component_type>
    </component_type_group>
    <!-- Correlation and Filter -->
    <component_type_group name="Operator" icon="" title="IEP.Operator.title" description="IEP.Operator.description">
        <!-- stream project and filter -->
        <component_type name="StreamProjectionAndFilter" icon="streamProjectionAndFilterx32.png" title="IEP.Operator.StreamProjectionAndFilter.title" description="IEP.Operator.StreamProjectionAndFilter.description" allowsChildren="false" visible="true" validator="org.netbeans.modules.iep.editor.validators.ValidateSchemaOwner">
            <property_group ref="/IEP/View/Node"/>
            <property_group ref="/IEP/Model/Entity">
                <property name="propertyEditor" editor="org.netbeans.modules.iep.editor.ps.DefaultCustomEditor"/>
                <property name="type" default="i18n.IEP.Operator.StreamProjectionAndFilter.title"/>
                <property name="inputType" default="i18n.IEP.IOType.stream"/>
                <property name="staticInputMaxCount" default="1000000"  access="&R;" />
                <property name="staticInputIdList" access="&R;" />
                <property name="outputType" default="i18n.IEP.IOType.stream"/>
                <property name="isSchemaOwner" default="true"/>
                <property name="palette" default="correlationAndFilter"/>
                <property name="helpID" default="iep_strprj_prop"/>
            </property_group>
            <property transient="false" category="IEP.Category.main" name="fromColumnList" title="IEP.Operator.StreamProjectionAndFilter.fromColumnList.title" description="IEP.Operator.StreamProjectionAndFilter.fromColumnList.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.TextAreaEditor" default="" renderer="string" access="" multiple="true"/>
            <property transient="false" category="IEP.Category.main" name="toColumnList" title="IEP.Operator.StreamProjectionAndFilter.toColumnList.title" description="IEP.Operator.StreamProjectionAndFilter.toColumnList.description" required="true" type="string" editor="org.netbeans.modules.iep.editor.tcg.ps.TextAreaEditor" default="" renderer="string" access="" multiple="true"/>